trigger:
  tags:
    include:
    - v*

resources:
- repo: self

variables:
  tag: '$(Build.SourceBranchName)'
  repository: 'ydemetriades/jira-release-notes'

stages:
- stage: Build
  displayName: Build image
  jobs:

  - job: Linux_Build
    displayName: Linux Job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build Linux Docker Image
      inputs:
        command: 'buildAndPush'
        repository: $(repository)
        dockerfile: '**/linux.dockerfile'
        containerRegistry: 'DockerHub'
        addPipelineData: false
        tags: |
          $(tag)
          latest

  - job: Windows_1809_Build
    displayName: Windows 1809 Job
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: Docker@2
      displayName: Build Windows 1809 Docker Image
      inputs:
        command: 'buildAndPush'
        repository: $(repository)
        dockerfile: '**/windows-1809.dockerfile'
        containerRegistry: 'DockerHub'
        addPipelineData: false
        tags: |
          $(tag)-win1809
          latest-win1809
